# server配置
server:
  port: 8080
  servlet:
    context-path: /
# 连接池配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wx_news?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  data:
    redis:
      host: 192.168.9.10
      port: 6379
      password: 123
      lettuce:
        pool:
          max-active: 8 #最大连接数
          max-idle: 8 #最大空闲连接数
          min-idle: 0 #最小空闲连接数
          max-wait: 100 #连接等待超时时间
# mybatis-plus的配置
mybatis-plus:
  type-aliases-package: com.news.domain.pojo

#jwt配置
jwt:
  token:
    tokenExpiration: 180 #有效时间,单位分钟
    tokenSignKey: GDPUwxNews123  #当前程序签名秘钥